### ISSUE TITLE
결제페이지 구현

### ISSUE THREAD

**Issue by yellow2041** [boostcamp-2020/Project07-A-RealTime-Seat-Reservation-System#34]
## TODO
- [x] 선택한 공연의 간단 정보 보여주기(선택 좌석 정보, 선택 공연회차 정보)
- [x] 선택한 좌석 수만큼 가격종류 선택 가능하도록 하기
- [x] 소켓으로 예매중임을 emit하기
